name: snowflake-demo
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.10
  - snowflake-snowpark-python
  - openssl=3.0.9  # Addresses this issue with oscrypto: https://github.com/wbond/oscrypto/issues/75
  - pip
  - pip:
    # Snowflake
    - snowflake-cli-labs==0.2.9
